theme = "lantern"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [80]
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "|"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
X = "select_line_above"

[keys.select]
X = "select_line_above"
